### PR TITLE
Allow fullscreen within iframe

### PR DESCRIPTION
**Pull request by vorph1**

### CODE REVIEW

**Comment by nickvergessen** [comment]
Can you describe why this would be needed or what this is fixing?

**Comment by vorph1** [comment]
It fixes the inability to open fullscreen embedded videos from within an external app (ie in wallabag)

**Comment by Failure404** [comment]
This is exactly what I need and solves my problem. Please approve.

**Comment by MahlodiM** [comment]
I have a  problem of embedding nextcloud into a site using iframe
Can anyone assist please

**Comment by MariusBluem** [comment]
> I have a problem of embedding nextcloud into a site using iframe
Can anyone assist please

Seems that this has nothing to do with this pull request ... Please open a new ticket. @MahlodiM

**Comment by hanzei** [comment]
@nickvergessen @MariusBluem Can this one be merged?

**Pull request merged**
