### PR TITLE
Upload of icons

### LINKED ISSUE #5: use of custom icons causes a security warning
I had opened https://github.com/nextcloud/apps/issues/20 because no separate repository existed that time.

### Affected apps
The external sites app

### Expected behaviour
The external sites app shouldn't cause a security warning when custom icons have been copied to the `./apps/external/img` directory and have been assigned to external site links. Additional icons in that directory should be excluded from the security check or the app should be extended to load icons from a different location which is not checked by the security function.

2016-12-11 11_19_26-administration - nextcloud

### Actual behaviour
The external sites app causes a security warning when custom icons are copied to the `./apps/external/img` directory and assigned to an external site link.

### Steps to reproduce
1. Copy a new icon file to the directory ./apps/external/img
2. Open Administration -> Additional settings -> External sites
3. Assign a new icon to an external site link.
4. Install a new app etc. so that a complete security check is forced. (unfortunately I don't know if it's possible to force a check from the command line.
5. A security warning is shown because an unknown file was found in the directory:

2016-12-12 20_09_23-mozilla firefox

### Server configuration
Operating system: Linux 3.2.82
Web server: Apache2 2.4.23
Database: MariaDB 5.5.53
PHP version: 5.6.23
Nextcloud version: 10.0.2

### Client configuration
Browser: Firefox 50.0.2
Operating system: Windows 7

### Logs
No errors have been logged

### LINKED ISSUE #16: White images on android navigation drawer
I get the images via API and use them on the navigation drawer in our android app.
The background color of this navigation drawer is white, which leads to not "showing" the external icons as they are then white on white.
Only settings.svg is working as it is black by default.

This is also the same if you look into the web UI and open the upper right menu.

I will need some black ones for proper displaying them.

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Allow to upload icons
- [x] Allow white/black images in parallel for UI/mobile clients
- [x] Move default icons on update/install
- [x] Add option to delete icons

Fix #16 
Fix #5 
Partly #36 

> nextcloud_-_2017-07-04_15 21 58

### CODE REVIEW

**Comment by nickvergessen** [comment]
@MariusBluem want to test this? Would be cool 😅

**Comment by MariusBluem** [comment]
Could we hide this „Durchsuchen“-box and simply show only the upload button (a bit larger)?

**Comment by nickvergessen** [comment]
Fixed, please review

**Comment by nickvergessen** [comment]
Fixed 🙈

**Pull request merged**
