### PR TITLE
Allow to redirect instead of IFrame for some setups

### LINKED ISSUE #27: Same origin policy forbids external pages
* configure https://google.com
* get following error: `Refused to display 'https://www.google.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

This is caused by https://github.com/nextcloud/server/pull/4072 because now this option is added to every request: https://github.com/nextcloud/server/blob/abe4a19cbc44b34bf171d1e9499c3e834364bd31/lib/base.php#L674-L674

@LukasReschke Any idea how to solve this? We need the external app.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #27 

@MorrisJobke in case you want to review this

### CODE REVIEW

**Comment by dan-nkl** [comment]
Also please add an option to open in new tab!

**Comment by nickvergessen** [comment]
Sorry that is not possible, because of how the menu navigation is generated by the server.

**Comment by pirate** [comment]
It is possible if it shares code with ownCloud @nickvergessen, I finished this recently for ownCloud and will be submitting a PR to nextcloud soon: https://github.com/owncloud/apps/pull/2221

It's a PR that adds a user configurable option for the link taget: '_blank', '_top', '_self' (new window/tab, replace current tab, open in iframe).

**Comment by nickvergessen** [comment]
Yeah well, our menu navigation is different from the owncloud one ;)

**Comment by pirate** [comment]
Cool, didn't realize the code diverged that much from OC.
 - [X] opening link in iframe (default)
 - [X] redirecting current window to link (finished in this PR)
 - [ ] opening link in new window

 To get the final new window functionality, could we do something like:
1. user clicks external site link, goes to `/external/1/`
2. on `/external/1/` the following JS executes:
```javascript
window.open(external_url);
window.history.back();
```
3. they are sent back to their previous page, and the link is opened in a new tab

**Pull request merged**
