### PR TITLE
Set CSP for icons

### PR DESCRIPTION
**Pull request by eglia**
Set the default Content Security Policy for the icon display controller.

This allows to use inline style attributes in SVG images.

### CODE REVIEW

**Comment by nickvergessen** [comment]
Hi @eglia 

thanks for your patch, it sounds valid. Do you have an image I can use for testing?

**Comment by eglia** [comment]
[icons.zip](https://github.com/nextcloud/external/files/3727909/icons.zip)
In the zip file are two icons, "mail.svg" and "mail-dark.svg". "mail.svg" contains style attributes to make the image white (for usage on dark background). Without the patch, both images are displayed as black in Firefox.

**Pull request merged**
