### PR TITLE
Add OCS endpoint for clients

### LINKED ISSUE #2: Allow sites just for a given language
When the user does not have the given language, the page should not be displayed.

### LINKED ISSUE #3: OCS endpoint to get the links
So they can be displayed in the mobile apps as well.

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] New settings panel
- [x] Controller instead of `index.php`
- [x] Controller instead of `ajax/`
- [x] Get rid of static `\OCA\External\External`
- [x] Add OCS endpoint for clients to get the sites
- [x] Allow to limit a link to a given language

Fix #3 
Fix #2

### CODE REVIEW

**Comment by nickvergessen** [comment]
@MorrisJobke please test, should be feature complete with this.
Doc of the endpoint is in README.md

**Comment by MorrisJobke** [comment]
* [ ] add a new entry until it gets saved and then change the title creates a second entry (POST instead of PUT is send)

**Comment by MorrisJobke** [comment]
Besides that it works nicely 👍

**Comment by MorrisJobke** [comment]
* [ ] very first entry that is added (ID 1) is not shown in the OCS api, but listed in the web UI
* [ ] entry is saved even when no icon is selected which looks weird - maybe preselect the first item in the icon list to remove this glitch

**Comment by nickvergessen** [comment]
> very first entry that is added (ID 1) is not shown in the OCS api, but listed in the web UI

Make sure you have the correct language. OCS filters by language already. Works here

**Comment by nickvergessen** [comment]
Fixed the icons in the OCS api, so they are full URLs now

**Comment by mario** [comment]
OK, so just to get some knowledge about this...

- do we have link types? (settings, "Get more space" below quota bar, regular sidebar links)?
- does the API throws in all languages and then the client decides which ones to use?

**Comment by marinofaggiana** [comment]
No SVG please

**Comment by nickvergessen** [comment]
> No SVG please

Since the sites are not new and svg was supported we can't change that.

> does the API throws in all languages and then the client decides which ones to use? 

The API only returns relevant sites (users language and "all languages")

> do we have link types? (settings, "Get more space" below quota bar, regular sidebar links)?

Currently there is no such thing, if that is required we can also add it. @MorrisJobke any specs about types that need to be supported?

**Comment by mario** [comment]
@nickvergessen 

"sidebar_regular", "sidebar_quota", and "settings", or whatever you want to call them. Sidebar quota should be limited to 1 item.

**Comment by nickvergessen** [comment]
Let's continue in https://github.com/nextcloud/external/issues/7

**Pull request merged**
