### PR TITLE
Make placeholders work everywhere

### PR DESCRIPTION
**Pull request by nickvergessen**
@dachinat thanks for notifying

Ref https://github.com/nextcloud/external/pull/66#issuecomment-362143569

### CODE REVIEW

**Comment by dachinat** [comment]
@nickvergessen thanks for your work. I think we'll have it patched until Nextcoud 14 if so.

**Comment by nickvergessen** [comment]
I will patch it in time for 13 ;)

**Comment by dachinat** [comment]
Great, thanks again!

**Comment by nickvergessen** [comment]
Released

**Pull request merged**
