### PR TITLE
Hijack the quota box in the files app

### PR DESCRIPTION
**Pull request by nickvergessen**
Requires https://github.com/nextcloud/server/pull/5305

### CODE REVIEW

**Comment by nickvergessen** [comment]
Current result:
dateien_-_nextcloud_-_2017-06-12_10 02 14

**Comment by jancborchardt** [comment]
People who don't know our architecture (most will not) will be bit confused about the label "External sites app". It doesn't seem very descriptive. Rather maybe "View details" or something, no? Where does it lead to, what can I expect, what does storage have to do with an external site?

**Comment by nickvergessen** [comment]
Hmm I think you dont understand the architecture here ;)
External sites app allows to add links in multiple positions, one is the quota. So the admin decides about the text and about the target of the link.

**Comment by jancborchardt** [comment]
Ok, but then the default text _when you add it_ should still be something other than "External sites app". :) More like " Do you need more space?" or "View details".

**Comment by MorrisJobke** [comment]
> Ok, but then the default text when you add it should still be something other than "External sites app". :) More like " Do you need more space?" or "View details".

This was just an example text by @nickvergessen 😉

**Comment by MorrisJobke** [comment]
I cherry picked all commits (except the revert) to stable12 and tested - worked just fine.

4a1e59a e67bc96 9fb1114 a59b433 

Thanks @nickvergessen for doing this.

**Pull request merged**
