### PR TITLE
Fix quota links in files

### PR DESCRIPTION
**Pull request by provokateurin**
Fixes https://github.com/nextcloud/external/issues/457
Fixes https://github.com/nextcloud/external/issues/173

~~This fix will only work for 28+ with the Files 2 Vue rewrite. Since there were no major complaints that this feature is broken I would skip backport to 26&27 because they require a completely different fix since they are still not in Vue.~~
Works on 25+

With this patch you even get the icons displayed in the quota and you can have more than one quota link (which wasn't prevented previously but it also didn't work either).

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by provokateurin** [comment]
Also works on 25-27 because the navigation was changed in 25 (as @skjnldsv suggested).

**Review by julien-nc — APPROVED** [review]
LGTM
Tested locally
Code looks good even if the Files app html structure might change which would break this.

**Pull request merged**
